version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: order_management
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
  server-go:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DB_USER: myuser
      DB_PASSWORD: 12345678
      DB_NAME: order_management
      DB_HOST: db
      DB_PORT: 3306

volumes:
  db-data:
  redis-data:
